# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

import argparse
import sys
import tempfile
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

_REPO_ROOT = Path(__file__).resolve().parent.parent
_ALEMBIC_INI = _REPO_ROOT / "pyrit" / "memory" / "alembic.ini"

# ANSI color codes
_RED = "\033[91m"
_RESET = "\033[0m"


def _print_error(message: str) -> None:
    """Print an error message in red to stderr."""
    print(f"{_RED}{message}{_RESET}", file=sys.stderr)


def _make_config(*, db_url: str) -> Config:
    """
    Build an Alembic Config pointed at a specific database URL.

    Args:
        db_url (str): SQLAlchemy database URL to use.

    Returns:
        Config: Configured Alembic config object.
    """
    cfg = Config(str(_ALEMBIC_INI))
    cfg.set_main_option("sqlalchemy.url", db_url)
    return cfg


def _cmd_generate(*, message: str, force: bool = False) -> None:
    """
    Generate a new Alembic revision from model changes.

    A fresh temporary SQLite database is created, upgraded to the current head,
    and then checked against the current models. If the check passes (schema matches),
    no migration is needed and the command fails. If the check fails (schema doesn't match),
    a migration is generated.

    Args:
        message (str): Human-readable migration message.
        force (bool): If True, generate a migration even if schema matches models.
                      Useful for manual migrations.

    Raises:
        SystemExit: If schema matches models and force=False.
    """
    with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as tmp:
        db_url = f"sqlite:///{tmp.name}"

    try:
        config = _make_config(db_url=db_url)
        command.upgrade(config, "head")

        # Check if schema matches current models
        try:
            command.check(config)
            # If check passes, schema already matches models
            if not force:
                _print_error("No schema changes detected. Use --force to generate an empty migration.")
                raise SystemExit(1)
            print("Generating migration even though schema matches models (--force used).")
        except AutogenerateDiffsDetected:
            # Check failed, meaning schema doesn't match models - proceed with generation
            pass

        command.revision(config, autogenerate=True, message=message)
        print("Migration file generated. Review it carefully before committing.")
    finally:
        Path(tmp.name).unlink(missing_ok=True)


def _cmd_check() -> None:
    """
    Verify that all migration scripts apply cleanly and schema matches models.

    Creates a clean temporary database, applies all migrations to head,
    and validates that the resulting schema matches the current memory models.
    """
    with tempfile.NamedTemporaryFile(suffix=".db", delete=False) as tmp:
        db_url = f"sqlite:///{tmp.name}"

    try:
        command.upgrade(_make_config(db_url=db_url), "head")
        command.check(_make_config(db_url=db_url))
    except Exception as e:
        _print_error(
            f"Migration check failed. Run the script in 'generate' mode to generate a new migration. Error: {e}"
        )
        raise SystemExit(1) from e
    finally:
        Path(tmp.name).unlink(missing_ok=True)


def _build_parser() -> argparse.ArgumentParser:
    """
    Build the CLI argument parser.

    Returns:
        argparse.ArgumentParser: Configured parser.
    """
    parser = argparse.ArgumentParser(
        description="PyRIT memory migration tool. Generate and validate migrations against clean databases."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="Generate a new migration from model changes.")
    gen.add_argument("-m", "--message", required=True, help="Migration message.")
    gen.add_argument("--force", action="store_true", help="Generate migration even if no changes detected.")

    sub.add_parser("check", help="Verify all migrations apply cleanly to a fresh database.")

    return parser


def main() -> int:
    """
    Dispatch the selected migration command.

    Returns:
        int: Process exit code.
    """
    if not _ALEMBIC_INI.exists():
        _print_error(f"Alembic config not found at {_ALEMBIC_INI}")
        return 1

    args = _build_parser().parse_args()

    if args.command == "generate":
        _cmd_generate(message=args.message, force=args.force)
    elif args.command == "check":
        _cmd_check()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
